# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       sailfishos-devicelock-method-fix-patch

# >> macros
BuildArch: noarch
# << macros

Summary:    Enable devicelock method switch
Version:    0.0.1
Release:    1
Group:      Qt/Qt
License:    TODO
Source0:    %{name}-%{version}.tar.bz2
Requires:   patchmanager
Requires:   jolla-settings-system = 0.2.26.1-10.38.1.jolla

%description
Proper patch enabling numeric - alphanumeric devicelock switch with no bug.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/usr/share/patchmanager/patches/sailfishos-devicelock-method-fix-patch
cp -r patch/* %{buildroot}/usr/share/patchmanager/patches/sailfishos-devicelock-method-fix-patch
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_datadir}/patchmanager/patches/sailfishos-devicelock-method-fix-patch
# >> files
# << files
